<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="WIB-DES-00840" name="com.wibmo.test.RechargeServicesPageTest" tests="1" failures="1" timestamp="20 Feb 2018 09:32:08 GMT" time="0.002" errors="0">
  <testcase name="clickOnMobileRecharge" time="0.002" classname="com.wibmo.test.RechargeServicesPageTest">
    <failure type="io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException" message="The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\prabhu.basavaraj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 0.0.0.0] 
Process output: [Appium] Welcome to Appium v1.7.2
[HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
uncaughtException: listen EADDRINUSE 0.0.0.0:4723
	{&quot;date&quot;:&quot;Tue Feb 20 2018 15:00:12 GMT+0530 (India Standard Time)&quot;,&quot;process&quot;:{&quot;pid&quot;:12948,&quot;uid&quot;:null,&quot;gid&quot;:null,&quot;cwd&quot;:&quot;C:\\Users\\prabhu.basavaraj\\workspace\\RechargeServices&quot;,&quot;execPath&quot;:&quot;C:\\Program Files\\nodejs\\node.exe&quot;,&quot;version&quot;:&quot;v6.11.5&quot;,&quot;argv&quot;:[&quot;C:\\Program Files\\nodejs\\node.exe&quot;,&quot;C:\\Users\\prabhu.basavaraj\\AppData\\Roaming\\npm\\node_modules\\appium\\build\\lib\\main.js&quot;,&quot;--port&quot;,&quot;4723&quot;,&quot;--address&quot;,&quot;0.0.0.0&quot;],&quot;memoryUsage&quot;:{&quot;rss&quot;:154333184,&quot;heapTotal&quot;:139153408,&quot;heapUsed&quot;:107173608,&quot;external&quot;:399255}},&quot;os&quot;:{&quot;loadavg&quot;:[0,0,0],&quot;uptime&quot;:3043751.5220885},&quot;trace&quot;:[{&quot;column&quot;:11,&quot;file&quot;:&quot;util.js&quot;,&quot;function&quot;:&quot;Object.exports._errnoException&quot;,&quot;line&quot;:1020,&quot;method&quot;:&quot;_errnoException&quot;,&quot;native&quot;:false},{&quot;column&quot;:20,&quot;file&quot;:&quot;util.js&quot;,&quot;function&quot;:&quot;exports._exceptionWithHostPort&quot;,&quot;line&quot;:1043,&quot;method&quot;:&quot;_exceptionWithHostPort&quot;,&quot;native&quot;:false},{&quot;column&quot;:14,&quot;file&quot;:&quot;net.js&quot;,&quot;function&quot;:&quot;Server._listen2&quot;,&quot;line&quot;:1262,&quot;method&quot;:&quot;_listen2&quot;,&quot;native&quot;:false},{&quot;column&quot;:10,&quot;file&quot;:&quot;net.js&quot;,&quot;function&quot;:&quot;listen&quot;,&quot;line&quot;:1298,&quot;method&quot;:null,&quot;native&quot;:false},{&quot;column&quot;:9,&quot;file&quot;:&quot;net.js&quot;,&quot;function&quot;:null,&quot;line&quot;:1408,&quot;method&quot;:null,&quot;native&quot;:false},{&quot;column&quot;:11,&quot;file&quot;:&quot;internal/process/next_tick.js&quot;,&quot;function&quot;:&quot;_combinedTickCallback&quot;,&quot;line&quot;:83,&quot;method&quot;:null,&quot;native&quot;:false},{&quot;column&quot;:9,&quot;file&quot;:&quot;internal/process/next_tick.js&quot;,&quot;function&quot;:&quot;process._tickCallback&quot;,&quot;line&quot;:104,&quot;method&quot;:&quot;_tickCallback&quot;,&quot;native&quot;:false}],&quot;stack&quot;:[&quot;Error: listen EADDRINUSE 0.0.0.0:4723&quot;,&quot;    at Object.exports._errnoException (util.js:1020:11)&quot;,&quot;    at exports._exceptionWithHostPort (util.js:1043:20)&quot;,&quot;    at Server._listen2 (net.js:1262:14)&quot;,&quot;    at listen (net.js:1298:10)&quot;,&quot;    at net.js:1408:9&quot;,&quot;    at _combinedTickCallback (internal/process/next_tick.js:83:11)&quot;,&quot;    at process._tickCallback (internal/process/next_tick.js:104:9)&quot;]}

">
      <![CDATA[io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [C:\Users\prabhu.basavaraj\AppData\Roaming\npm\node_modules\appium\build\lib\main.js, --port, 4723, --address, 0.0.0.0] 
Process output: [Appium] Welcome to Appium v1.7.2
[HTTP] Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
uncaughtException: listen EADDRINUSE 0.0.0.0:4723
	{"date":"Tue Feb 20 2018 15:00:12 GMT+0530 (India Standard Time)","process":{"pid":12948,"uid":null,"gid":null,"cwd":"C:\\Users\\prabhu.basavaraj\\workspace\\RechargeServices","execPath":"C:\\Program Files\\nodejs\\node.exe","version":"v6.11.5","argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\prabhu.basavaraj\\AppData\\Roaming\\npm\\node_modules\\appium\\build\\lib\\main.js","--port","4723","--address","0.0.0.0"],"memoryUsage":{"rss":154333184,"heapTotal":139153408,"heapUsed":107173608,"external":399255}},"os":{"loadavg":[0,0,0],"uptime":3043751.5220885},"trace":[{"column":11,"file":"util.js","function":"Object.exports._errnoException","line":1020,"method":"_errnoException","native":false},{"column":20,"file":"util.js","function":"exports._exceptionWithHostPort","line":1043,"method":"_exceptionWithHostPort","native":false},{"column":14,"file":"net.js","function":"Server._listen2","line":1262,"method":"_listen2","native":false},{"column":10,"file":"net.js","function":"listen","line":1298,"method":null,"native":false},{"column":9,"file":"net.js","function":null,"line":1408,"method":null,"native":false},{"column":11,"file":"internal/process/next_tick.js","function":"_combinedTickCallback","line":83,"method":null,"native":false},{"column":9,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":104,"method":"_tickCallback","native":false}],"stack":["Error: listen EADDRINUSE 0.0.0.0:4723","    at Object.exports._errnoException (util.js:1020:11)","    at exports._exceptionWithHostPort (util.js:1043:20)","    at Server._listen2 (net.js:1262:14)","    at listen (net.js:1298:10)","    at net.js:1408:9","    at _combinedTickCallback (internal/process/next_tick.js:83:11)","    at process._tickCallback (internal/process/next_tick.js:104:9)"]}


	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:149)
	at com.wibmo.base.TestBase.setUp(TestBase.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://0.0.0.0:4723/wd/hub/status] to be available after 120003 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
	at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:113)
	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:136)
	... 25 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:147)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
	... 27 more
]]>
    </failure>
  </testcase> <!-- clickOnMobileRecharge -->
</testsuite> <!-- com.wibmo.test.RechargeServicesPageTest -->
